apiVersion: apps/v1
kind: Deployment
metadata:
  name: parrot-blue
  namespace: parrot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: parrot
      version: blue
  template:
    metadata:
      labels:
        app: parrot
        version: blue
    spec:
      containers:
        - name: parrot-blue
          resources:
            requests:
              memory: 64Mi
              cpu: 200m
            limits:
              memory: 64Mi
              cpu: 200m
          image: 886436933321.dkr.ecr.us-east-1.amazonaws.com/parrot:1
          ports:
            - containerPort: 3000
          env:
            - name: WEBSITE_TITLE
              valueFrom:
                configMapKeyRef:
                  name: blue
                  key: TITLE
            - name: WEBSITE_IMAGE
              valueFrom:
                configMapKeyRef:
                  name: blue
                  key: IMAGE

