# This pipeline will run that builds and deploys the poc-healthcare-payer-demo-app docker container any time a PR is Raised and Merged against "Main" Branch.
name: build-and-push
on:
  push:
    branches:
      - main #This name is temporary meanwhile Tatiane rename this branch.
  workflow_dispatch:
# Used for getting permissions to AWS resources through an OIDC federation
permissions:
  id-token: write
  contents: read  

env:
  AWS_REGION: us-east-1
  ECR_REPO: parrot

jobs:
  build:
    runs-on: ubuntu-latest
    steps:                       
      # Configure AWS credentials using assumed role
      - name: 'Configure AWS credentials'
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - uses: actions/checkout@v2                  
      - name: Login to ECR
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.AWS_ACCOUNT }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPO }} ##image
          username: ${{ secrets.AWS_ACCESS_KEY_ID }}
          password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Create ECR repository if it does not exist
        run: |
          REPO_NAME=${{ env.ECR_REPO }}
          aws ecr describe-repositories --repository-names $REPO_NAME || \
          aws ecr create-repository --repository-name $REPO_NAME

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./app/
          file: ./app/Dockerfile
          push: true
          tags: ${{ secrets.AWS_ACCOUNT }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPO }}:${{github.run_number}}
          
